version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-sasl
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network-sasl

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-sasl
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
      - "29093:29093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      
      # Apenas listeners SASL (remover plaintext)
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka:9093,SASL_PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_PLAINTEXT_HOST:SASL_PLAINTEXT
      
      # Forçar uso de SASL para comunicação entre brokers
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      
      # Configuração de Zookeeper (sem autenticação)
      KAFKA_ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_ZOOKEEPER_SET_ACL: "false"
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf -Dzookeeper.sasl.client=false"
      
      # Replicação e logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      
      # Debug para inicialização
      KAFKA_DEBUG: "all"
    volumes:
      - ./kafka_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    networks:
      - kafka-network-sasl

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry-sasl
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9093
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_PLAINTEXT
      SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: PLAIN
      SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="schema-registry" password="schema-registry-password";'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_OPTS: "-Djava.security.auth.login.config=/etc/schema-registry/schema-registry_jaas.conf"
    volumes:
      - ./schema-registry-jaas.conf:/etc/schema-registry/schema-registry_jaas.conf
    networks:
      - kafka-network-sasl

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-sasl
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "8080:8080"
    environment:
      # Apenas um cluster com SASL
      KAFKA_CLUSTERS_0_NAME: kafka-secure
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";'
    networks:
      - kafka-network-sasl

networks:
  kafka-network-sasl:
    driver: bridge
